name = "bayan"
main = "src/index.js"
compatibility_date = "2026-07-01"
workers_dev = true

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "bayan"
database_id = "9eba6f6c-a118-4b18-a15c-8fddd43c29f3"

[observability]
enabled = true
